package(licenses = ["notice"])

go_library(
    name = "reviver",
    srcs = ["reviver.go"],
    importpath = "gvisor.dev/gvisor/tools/issue_reviver/reviver",
    visibility = [
        "//tools/issue_reviver:__subpackages__",
    ],
)
